Update to rails 5.1.4
Remove broken log settings from production.rb

[#150860119]

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,13 +1,29 @@
-#!/usr/bin/env bash
-set -e
+#!/usr/bin/env ruby
+require 'pathname'
+require 'fileutils'
+include FileUtils
 
-echo '== Installing dependencies =='
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
 
-bundle install
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-echo "== Updating database =="
-bin/rails db:migrate
-bin/rails db:migrate RAILS_ENV=test
+chdir APP_ROOT do
+  # This script is a way to update your development environment automatically.
+  # Add necessary update steps to this file.
 
-echo "== Removing old logs and tempfiles =="
-bin/rails log:clear tmp:clear
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
+
+  puts "\n== Updating database =="
+  system! 'bin/rails db:migrate'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
