kill's still failing; trying crude try/catch

diff --git a/scripts/stop_server b/scripts/stop_server
--- a/scripts/stop_server
+++ b/scripts/stop_server
@@ -2,5 +2,10 @@
 TARGETS=$(lsof -t -i:80)
 if [[ ${TARGETS:+1} ]]
 then
-  kill TARGETS
+  {
+    kill TARGETS &&
+    echo "success"
+  } || {
+    echo "failure"
+  }
 fi
